# Generated by Django 5.2.17 on 2026-09-29 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FollowUp',
        ),
    ]
