# Generated by Django 5.2.17 on 2026-09-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_emailtemplate_emailcampaign_emaillog_campaign'),
        ('leads', '0003_contact_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='leads',
            field=models.ManyToManyField(related_name='campaigns', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='emails/'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='body',
            field=models.TextField(help_text='Use {{ company_name }} or {{ unsubscribe_link }} as placeholders.'),
        ),
    ]
