# Generated by Django 5.2.17 on 2026-09-30 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_emailcampaign_leads_emaillog_attachment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignSequenceStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.IntegerField()),
                ('delay_days', models.IntegerField(default=0, help_text='Days to wait before sending this step')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='emails.emailcampaign')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emails.emailtemplate')),
            ],
            options={
                'ordering': ['step_order'],
            },
        ),
        migrations.AddField(
            model_name='emaillog',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emails.campaignsequencestep'),
        ),
    ]
