# Generated by Django 5.2.17 on 2026-09-30 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("file_path", models.FileField(upload_to="imports/%Y/%m/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UPLOADED", "Uploaded"),
                            ("MAPPED", "Columns mapped"),
                            ("PREVIEWED", "Preview ready"),
                            ("QUEUED", "Queued"),
                            ("RUNNING", "Importing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="UPLOADED",
                        max_length=20,
                    ),
                ),
                ("detected_columns", models.JSONField(blank=True, default=list)),
                ("column_mapping", models.JSONField(blank=True, default=dict)),
                ("total_rows", models.IntegerField(default=0)),
                ("created_rows", models.IntegerField(default=0)),
                ("merged_rows", models.IntegerField(default=0)),
                ("review_rows", models.IntegerField(default=0)),
                ("rejected_rows", models.IntegerField(default=0)),
                ("warned_rows", models.IntegerField(default=0)),
                ("preview", models.JSONField(blank=True, default=dict)),
                ("rejections", models.JSONField(blank=True, default=list)),
                ("error_log", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
