# Generated by Django 5.2.17 on 2026-09-30 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='column_mapping',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
