# Generated by Django 5.2.17 on 2026-09-30 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GenerationJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("state", models.CharField(max_length=100)),
                ("district", models.CharField(blank=True, default="", max_length=100)),
                ("city", models.CharField(blank=True, default="", max_length=100)),
                ("industry", models.CharField(max_length=100)),
                (
                    "keywords",
                    models.TextField(help_text="Comma separated search keywords"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Waiting to start"),
                            ("RUNNING", "Running"),
                            ("PAUSED", "Paused"),
                            ("STOPPED", "Stopped"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("max_websites", models.PositiveIntegerField(default=50)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("paused_at", models.DateTimeField(blank=True, null=True)),
                ("stopped_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("heartbeat_at", models.DateTimeField(blank=True, null=True)),
                (
                    "current_query",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "current_website",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("websites_found", models.IntegerField(default=0)),
                ("leads_found", models.IntegerField(default=0)),
                ("valid_leads", models.IntegerField(default=0)),
                ("duplicate_leads", models.IntegerField(default=0)),
                ("rejected_leads", models.IntegerField(default=0)),
                ("needs_review", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, default="")),
                ("log", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Industry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                "verbose_name_plural": "industries",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(db_index=True, max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["state", "name"],
                "unique_together": {("state", "name")},
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cities",
                        to="lead_generation.district",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "cities",
                "ordering": ["name"],
                "unique_together": {("district", "name")},
            },
        ),
        migrations.CreateModel(
            name="SearchKeyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.CharField(max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "industry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keywords",
                        to="lead_generation.industry",
                    ),
                ),
            ],
            options={
                "ordering": ["keyword"],
                "unique_together": {("industry", "keyword")},
            },
        ),
    ]
