# Generated by Django 5.2.17 on 2026-09-29 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_generation', '0001_initial'),
        ('leads', '0002_lead_source_query_lead_source_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuplicateResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scraped_data', models.JSONField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SKIPPED', 'Skipped'), ('UPDATED', 'Updated'), ('MERGED', 'Merged')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('existing_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_resolutions', to='leads.company')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicates', to='lead_generation.generationjob')),
            ],
        ),
    ]
