# Generated by Django 5.2.17 on 2026-09-30 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_generation', '0002_duplicateresolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationjob',
            name='is_headless',
            field=models.BooleanField(default=True),
        ),
    ]
