# Generated by Django 5.2.17 on 2026-09-30 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                (
                    "legal_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("industry", models.CharField(blank=True, default="", max_length=100)),
                (
                    "company_type",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("website", models.URLField(blank=True, default="", max_length=500)),
                (
                    "company_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "company_phone",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "cin",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=21
                    ),
                ),
                (
                    "gstin",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=15
                    ),
                ),
                (
                    "linkedin_url",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                ("google_maps_url", models.TextField(blank=True, default="")),
                (
                    "normalized_name",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                (
                    "normalized_domain",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                (
                    "normalized_email",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=254
                    ),
                ),
                (
                    "normalized_phone",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=20
                    ),
                ),
                (
                    "identity_status",
                    models.CharField(
                        choices=[
                            ("UNVERIFIED", "Unverified"),
                            ("TITLE_GUESS", "Name guessed from page title"),
                            ("SITE_CONFIRMED", "Name confirmed on company website"),
                            ("GST_MATCHED", "Matched to GSTIN"),
                            ("ROC_MATCHED", "Matched to MCA/ROC record"),
                        ],
                        default="UNVERIFIED",
                        max_length=20,
                    ),
                ),
                (
                    "email_status",
                    models.CharField(
                        choices=[
                            ("UNKNOWN", "Not checked"),
                            ("SYNTAX_OK", "Format valid"),
                            ("MX_OK", "Domain accepts mail"),
                            ("NO_MX", "Domain rejects mail"),
                            ("BOUNCED", "Bounced"),
                        ],
                        default="UNKNOWN",
                        max_length=20,
                    ),
                ),
                (
                    "phone_status",
                    models.CharField(
                        choices=[
                            ("UNKNOWN", "Not checked"),
                            ("PLAUSIBLE", "Valid format"),
                            ("MOBILE_OK", "Valid mobile"),
                            ("LANDLINE_OK", "Valid landline"),
                            ("TOLLFREE_OK", "Toll free"),
                            ("INTL_OK", "Valid international"),
                            ("WRONG", "Wrong number"),
                        ],
                        default="UNKNOWN",
                        max_length=20,
                    ),
                ),
                (
                    "data_quality_score",
                    models.PositiveSmallIntegerField(db_index=True, default=0),
                ),
                ("source", models.CharField(blank=True, default="", max_length=100)),
                ("source_history", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "companies",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("cin", ""), _negated=True),
                        fields=("cin",),
                        name="uniq_company_cin",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("gstin", ""), _negated=True),
                        fields=("gstin",),
                        name="uniq_company_gstin",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("normalized_domain", ""), _negated=True),
                        fields=("normalized_domain",),
                        name="uniq_company_domain",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("normalized_email", ""), _negated=True),
                        fields=("normalized_email",),
                        name="uniq_company_email",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("normalized_phone", ""), _negated=True),
                        fields=("normalized_phone",),
                        name="uniq_company_phone",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "designation",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "department",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                (
                    "normalized_email",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=254
                    ),
                ),
                ("mobile", models.CharField(blank=True, default="", max_length=20)),
                (
                    "direct_phone",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "linkedin_url",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="leads.company",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_primary", "id"],
            },
        ),
        migrations.CreateModel(
            name="DuplicateReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("incoming", models.JSONField()),
                ("match_score", models.PositiveSmallIntegerField(default=0)),
                (
                    "match_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("origin", models.CharField(blank=True, default="", max_length=50)),
                (
                    "generation_job_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "import_job_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Waiting for review"),
                            ("KEPT_EXISTING", "Kept existing record"),
                            ("USED_NEW", "Replaced with new data"),
                            ("MERGED", "Merged"),
                            ("NOT_DUPLICATE", "Saved as a separate company"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "existing_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duplicate_reviews",
                        to="leads.company",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Plant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plant_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("plant_address", models.TextField(blank=True, default="")),
                (
                    "city",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=100
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=100
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=100
                    ),
                ),
                (
                    "pin_code",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=6
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("is_primary", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plants",
                        to="leads.company",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_primary", "id"],
            },
        ),
        migrations.CreateModel(
            name="Suppression",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=254
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=20
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("UNSUBSCRIBED", "Unsubscribed"),
                            ("BOUNCED", "Hard bounced"),
                            ("COMPLAINED", "Marked as spam"),
                            ("MANUAL", "Added manually"),
                        ],
                        default="UNSUBSCRIBED",
                        max_length=20,
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("email", ""), _negated=True),
                        fields=("email",),
                        name="uniq_suppression_email",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("phone", ""), _negated=True),
                        fields=("phone",),
                        name="uniq_suppression_phone",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New Lead"),
                            ("CALLED", "Called"),
                            ("PROFILE_SENT", "Profile Sent"),
                            ("FOLLOW_UP_DUE", "Follow-up Due"),
                            ("REQUIREMENT_RECEIVED", "Requirement Received"),
                            ("CONVERTED", "Converted"),
                            ("NOT_RELEVANT", "Not Relevant"),
                        ],
                        db_index=True,
                        default="NEW",
                        max_length=30,
                    ),
                ),
                (
                    "lead_source",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("source_query", models.TextField(blank=True, default="")),
                ("source_url", models.URLField(blank=True, default="", max_length=500)),
                (
                    "generation_job_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "import_job_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("first_contact_date", models.DateField(blank=True, null=True)),
                ("profile_sent", models.BooleanField(default=False)),
                ("profile_sent_at", models.DateField(blank=True, null=True)),
                (
                    "follow_up_date",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                ("follow_up_count", models.PositiveSmallIntegerField(default=0)),
                ("last_contacted_at", models.DateTimeField(blank=True, null=True)),
                ("requirement", models.TextField(blank=True, default="")),
                ("quotation", models.TextField(blank=True, default="")),
                ("remarks", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leads",
                        to="leads.company",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to="leads.contact",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="leads_lead_status_7559b2_idx",
                    ),
                    models.Index(
                        fields=["follow_up_date", "status"],
                        name="leads_lead_follow__27fcb9_idx",
                    ),
                ],
            },
        ),
    ]
