# Generated by Django 5.2.17 on 2026-09-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='source_query',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='source_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
