# Generated by Django 5.2.17 on 2026-09-30 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_contact_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('FOLLOW_UP', 'Follow-up'), ('REQUIREMENT', 'Requirement'), ('QUOTATION', 'Quotation'), ('NEGOTIATION', 'Negotiation'), ('CONVERTED', 'Converted'), ('LOST', 'Lost')], default='NEW', max_length=50),
        ),
    ]
