# Generated by Django 5.2.17 on 2026-09-30 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_alter_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('INTERESTED', 'Interested'), ('REQUIREMENT_RECEIVED', 'Requirement Received'), ('QUOTATION_SENT', 'Quotation Sent'), ('NEGOTIATION', 'Negotiation'), ('CONVERTED', 'Converted'), ('NOT_INTERESTED', 'Not Interested'), ('WRONG_CONTACT', 'Wrong Contact'), ('INVALID', 'Invalid'), ('CLOSED_LOST', 'Closed / Lost')], default='NEW', max_length=50),
        ),
    ]
